### ISSUE TITLE
Coordinates don't match for NCC/NorESM1-ME or MIROC/MIROC5

### ISSUE THREAD

**Issue by ellesmith88** [roocs/clisops#56]
Issue in ESMValTool - some coordinate points vary for different files of this dataset (for different time range). This fix removes these inaccuracies by rounding the coordinates.

can be found here: https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/cmor/_fixes/cmip5/noresm1_me.py

This seems to have been corrected - can't find this problem in any of the NCC/NorESM1-ME Amon tas datasets

**Comment by sol1105** [comment]
I think this can be closed. For the regrid operator `clisops/core/regrid/Grid._cap_precision` was introduced, conducting such a fix generally for datasets to be remapped since a few CMIP6 datasets are subject to this issue. This fix could also generally applied for other operators if needed. The precision is defined in the `clisops/etc/roocs.ini`:

```
[clisops:coordinate_precision]
hor_coord_decimals = 6
vert_coord_decimals = 6
```
